# Generated by Django 2.2.6 on 2019-10-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='public',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
