# Generated by Django 2.2.6 on 2019-10-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_topic_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='public',
        ),
    ]
