# Generated by Django 2.2.6 on 2019-10-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_remove_topic_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='public',
            field=models.CharField(default=False, max_length=20),
            preserve_default=False,
        ),
    ]
