# Generated by Django 2.2.6 on 2019-10-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_auto_20191017_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='public',
            field=models.TextField(verbose_name=True),
        ),
    ]
