# Generated by Django 2.2.6 on 2019-10-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0009_auto_20191017_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='public',
            field=models.BooleanField(),
        ),
    ]
