# Generated by Django 2.2.6 on 2019-10-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0025_topic_ma'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='myt',
            field=models.TextField(default='hello'),
        ),
    ]
