# Generated by Django 2.2.6 on 2019-10-18 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0027_auto_20191018_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='public',
            new_name='ppp',
        ),
    ]
