# Generated by Django 2.2.6 on 2019-10-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0028_auto_20191018_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='ppp',
            field=models.BooleanField(verbose_name='True'),
        ),
    ]
