# Generated by Django 2.2.6 on 2019-10-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0031_auto_20191018_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='myt',
            field=models.TextField(default='hello2'),
        ),
    ]
