# Generated by Django 2.2.6 on 2019-10-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0036_topic_ma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='ma',
            field=models.EmailField(default='s@163.com', max_length=254),
        ),
    ]
