# Generated by Django 2.2.6 on 2019-10-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0039_auto_20191018_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='ma',
            field=models.EmailField(default='ha@163.com', max_length=254),
        ),
    ]
