# Generated by Django 2.2.6 on 2019-10-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0040_auto_20191018_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='ma',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='public',
        ),
    ]
